### ISSUE TITLE
panic: livereload: no such file or directory

### ISSUE THREAD

**Issue by Obsinqsob01** [mattn/echo-livereload#2]
Mmm I installl this package but in the moment that I try to run my server I got this error:

> panic: livereload: no such file or directory
> goroutine 1 [running]:
github.com/mattn/echo-livereload.LiveReloadWithConfig(0x8cfe48, 0x7ffef8f0917e, 0x24, 0x8b0eea, 0x6, 0xc4200a84b0, 0xc4200a6040)
	/home/obsinqsob01/golang/src/github.com/mattn/echo-livereload/livereload.go:65 +0x230
github.com/mattn/echo-livereload.LiveReload(0xc420178000)
	/home/obsinqsob01/golang/src/github.com/mattn/echo-livereload/livereload.go:37 +0x3f
main.main()
	/home/obsinqsob01/golang/src/comm/main.go:19 +0x55
exit status 2

I Do not know is it's error of my machine, version or something...

**Comment by hugows** [comment]
Not sure this was what I wanted, but https://github.com/markbates/refresh is working for me.

**Comment by mattn** [comment]
You can you [goemon](https://github.com/mattn/goemon) too.
